# Request Types
CREATE_QUEUE=0
DELETE_QUEUE=1
LIST_QUEUES=2
PRODUCE=3
CONSUME=4
ACK=5
LIST_BROKERS=6

# Response Error Types
INTERNAL_SERVER_ERROR=1
INVALID_REQUEST=2
NOT_LEADER_FOR_PARTITION=3
UNKNOWN_QUEUE_OR_PARTITION=4
REQUEST_TIMED_OUT=5
INVALID_REQUEST=6
RECORD_LIST_TOO_LARGE=7
MESSAGE_TOO_LARGE=8

# Request Required
ENDIAS = "little"
