# Generic
BOOL_SIZE = 1
INT_SIZE = 4
LONG_SIZE = 4

# Request Types
CREATE_QUEUE = 1
DELETE_QUEUE = 2
LIST_QUEUES = 3
PRODUCER_CONNECT = 4
PRODUCE = 5
CONSUMER_CONNECT = 6
CONSUME = 7
ACK = 8
LIST_BROKERS = 9
BEGIN_TRANSACTION = 10
COMMIT_TRANSACTION = 11
GET_CONTROLLERS_CONNECTION_INFO = 12
GET_CONTROLLER_LEADER_ID = 13

# Response Error Types
NO_ERROR = 0
INTERNAL_SERVER_ERROR=1
INVALID_REQUEST=2
NOT_LEADER_FOR_PARTITION=3
UNKNOWN_QUEUE_OR_PARTITION=4
REQUEST_TIMED_OUT=5
INVALID_REQUEST=6
RECORD_LIST_TOO_LARGE=7
MESSAGE_TOO_LARGE=8

# Generic Error Codes
CONNECTION_ERROR = -1
TIMEOUT_ERROR = -2

# Request Required
ENDIAS = "little"

# Request Value Keys
USERNAME = 1
PASSWORD = 2
REQUEST_TYPE = 3
QUEUE_NAME = 4
PARTITIONS = 5
REPLICATION_FACTOR = 6
TRANSACTIONAL_ID = 7
TRANSACTION_ID = 8
PRODUCER_ID = 9
PRODUCER_EPOCH = 10
PARTITION = 11
MESSAGE = 12

# Response Value Keys
OK = 4
LEADER_ID = 5
CONTROLLER_CONNECTION_INFO = 6

# SASL AUTHENTICATION TYPES
SASL_BASIC_AUTH = "basic"
SASL_CLIENT_CERT = "client_cert"
