import ctypes

# Generic
BOOL_SIZE = ctypes.sizeof(ctypes.c_bool)
INT_SIZE = ctypes.sizeof(ctypes.c_int)
LONG_LONG_SIZE = ctypes.sizeof(ctypes.c_longlong)

# Request Types
PING = 0
CREATE_QUEUE = 1
DELETE_QUEUE = 2
PRODUCE = 3
CONSUME = 4
ACK = 5
GET_CONTROLLERS_CONNECTION_INFO = 6
GET_CONTROLLER_LEADER_ID = 7
GET_QUEUE_PARTITIONS_INFO = 8
REGISTER_CONSUMER = 9
GET_CONSUMER_ASSIGNED_PARTITIONS = 10
REGISTER_TRANSACTION_GROUP = 11
BEGIN_TRANSACTION = 12
FINALIZE_TRANSACTION = 13
VERIFY_TRANSACTION_GROUP_CREATION = 14

# Response Error Types
NO_ERROR = 0
INTERNAL_SERVER_ERROR = 1
INCORRECT_REQUEST_BODY = 2
INCORRECT_PARTITION_NUMBER = 3
QUEUE_DOES_NOT_EXIST = 4
PARTITION_DOES_NOT_EXIST = 5
INCORRECT_ACTION = 6
INCORRECT_LEADER = 7
INCORRECT_MESSAGE_COUNT = 8
TOO_MANY_BYTES_RECEIVED = 9
UNAUTHORIZED = 10
TOO_FEW_AVAILABLE_NODES = 11
UNASSIGNED_LEADERSHIP = 12
CONSUMER_NOT_FOUND = 13
INCORRECT_CONSUMER_GROUP_ID = 14
QUEUE_ALREADY_EXISTS = 15
CONSUMER_UNREGISTERED = 16

# Generic Error Codes
CONNECTION_ERROR = -1
TIMEOUT_ERROR = -2

# Request Required
ENDIAS = "little"

# Request Value Keys
USERNAME = 1
PASSWORD = 2
REQUEST_TYPE = 3
QUEUE_NAME = 4
PARTITIONS = 5
REPLICATION_FACTOR = 6
PARTITION = 7
MESSAGES = 8
CONSUMER_GROUP_ID = 9
CONSUME_FROM = 10
CONSUMER_ID = 11
MESSAGE_OFFSET = 12
READ_SINGLE_OFFSET_ONLY = 13
REGISTERED_QUEUES = 14
TRANSACTION_GROUP_ID = 15
TRANSACTION_ID = 16
COMMIT_TRANSACTION = 17

# Response Value Keys
RES_VAL_OK = 1
RES_VAL_LEADER_ID = 2
RES_VAL_CONTROLLER_CONNECTION_INFO = 3
RES_VAL_TOTAL_PARTITIONS = 4
RES_VAL_PARTITION_NODE_CONNECTION_INFO = 5
RES_VAL_CONSUMER_ID = 6
RES_VAL_ASSIGNED_PARTITIONS = 7
RES_VAL_MESSAGES = 8
RES_VAL_QUEUE_CREATED = 9
RES_VAL_QUEUE_DELETED = 10
RES_VAL_TRANSACTION_GROUP_ID = 11
RES_VAL_TRANSACTION_ID = 12

# Consumer Logic
CONSUME_EARLIEST="earliest"
CONSUME_LATEST="latest"

# Message Structure
MESSAGE_ID_OFFSET=16
MESSAGE_TIMESTAMP_OFFSET=24
MESSAGE_KEY_SIZE_OFFSET=41
MESSAGE_PAYLOAD_SIZE_OFFSET=45
MESSAGE_METADATA_END_OFFSET=49